### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by rmdort** [open-intent-io/open-intent#56]
Getting this error when i run `open-intent project start mychatbot`

```
Starting: /Users/xxx/Sites/mychatbot/app.js...
  project will restart on model changes.
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/xxx/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/open-intent.node, 1): no suitable image found.  Did find:
        /Users/xxx/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/open-intent.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/xxx/Sites/mychatbot/node_modules/open-intent/lib/chatbot-api/chatbot-factory.js:40:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
```

Environment

```
node - 4.2.6
npm - 3.10.8
```

Although running using docker works fine

**Comment by clems4ever** [comment]
Hello rmdort, I will have a look at the issue. It seems the C++ core is not in the npm package.

**Comment by clems4ever** [comment]
Hello @rmdort, this is due to the fact that we do not support Mac operating system yet. I created issue #60 for this gap and I'm closing this one. Thanks.
